### ISSUE TITLE
get_moving_averageについて

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#15]
個人的には
sma_ema引数を無くし、get_sma,get_emaの２関数を作ればいいと思うのですが、どうでしょうか。
引数が増えれば増えるほど、ややこしいコードになるので、関数を分けて、中身を共通関数でまとめる方が利便性、保守性が高くなると思います。

**Comment by ttskmnj** [comment]
現状のget_moving_averageを共通関数として、get_sma,get_emaから呼び出すという形ですか？

**Comment by Akira-Taniguchi** [comment]
はい、そんなイメージです。get_moving_averageを内部関数にして。

**Comment by ttskmnj** [comment]
修正しました。
