### ISSUE TITLE
外部モジュールの取り込みもれ

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#25]
>import numpy as np

とありますが、setup.pyに外部モジュールの参照設定がないため、このままではPythonから怒られます。

setup.pyの

>install_requires=['zaifapi==1.3.1']

を

>install_requires=['zaifapi==1.3.1', 'numpy==1.12.0']

に修正しておきましょう。
現時点でのnumpyの最新バージョンは1.12.0だそうなので。
参考：https://pypi.python.org/pypi/numpy

**Comment by ttskmnj** [comment]
了解です。
sqliteとsqlalchemyも追加しないとダメですよね？

**Comment by Akira-Taniguchi** [comment]
動作確認のさい、追加したので、こちらはくろーずします。
