### ISSUE TITLE
不要(?)なコメント

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#26]
moving_average.pyの冒頭に

>\# moving_average.py

とありますが、あまり必要性を感じません。
削除してはどうでしょうか。

**Comment by Akira-Taniguchi** [comment]
moving_average.pyの冒頭に

># moving_average.py

とありますが、あまり必要性を感じません。
削除してはどうでしょうか。

**Comment by ttskmnj** [comment]
修正しました。
