### ISSUE TITLE
TradelogsとMovingAverageの移動

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#27]
db.pyはあらゆる機能から参照されることになるとおもわれる共通モジュールになります。

一方、TradelogsとMovingAverageは、少なくとも今のところget_ema,get_smaからしか利用されない想定です。
なので、今のうちにPythonファイルごと分けてしまいましょう。

zaifbot/zaifbot/bot_common/db.py ←ここにZaifBotDb
zaifbot/zaifbot/modules/moving_averrage.py ←ここにTradelogsとMovingAverageとか、データアクセスオブジェクトを記述する

という感じで。

**Comment by ttskmnj** [comment]
対応しました。
