### ISSUE TITLE
_LIMIT_COUNTの宣言位置

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#28]
_LIMIT_COUNTをget_moving_averageの外で宣言すれば

>def get_moving_average(currency_pair, count=1000, to_epoch_time=int(time.time()), period='1d', length=5, sma_ema='sma'):

のcountのデフォルト値も定数で指定できます。

**Comment by ttskmnj** [comment]
修正しました。
