### ISSUE TITLE
ZaifのAPIの実行方法

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#4]

**Comment by Akira-Taniguchi** [comment]
せっかくなので、外部ライブラリを使用ください。宣伝もかねて。
該当仮想環境で
 pip install zaifapi
とすれば利用可能となります。

取引履歴情報を取得する場合は

from zaifapi import ZaifPublicApi
public_api = ZaifPublicApi()
result = public_api. everything('ohlc_data', currency_pair, {'period': '3d', 'count': 10})
print(result)

みたいな感じです。

**Comment by ttskmnj** [comment]
メソッド名ですが、historyなどはどうでしょうか？

**Comment by Akira-Taniguchi** [comment]
メソッドeverythingは第一引数にAPIの名称を指定することによって、すべての公開APIを実行できるようにしています。例えば「get_info」と指定すればget_infoAPIの実行結果が取得できるため、historyという名前は妥当ではないと想います。

英語的な感覚がないので、いい名前案をいただけたらというのが意図となります。

本質とは違う問題なので、このチケットはクローズします。
