### ISSUE TITLE
count判定時のミス

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#44]
get_moving_averageにおいて、

>start_time = to_epoch_time - ((count + length) * PERIOD_SECS[period])
>count = min(count, LIMIT_COUNT)

とありますが、先にcountを決めておかないとstart_timeとの整合性がなくなるので、

>count = min(count, LIMIT_COUNT)
>start_time = to_epoch_time - ((count + length) * PERIOD_SECS[period])

になるとおもうのですが、どうでしょうか。

**Comment by ttskmnj** [comment]
確かにそうですね。
修正しました。
