### ISSUE TITLE
sessionのclose

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#62]
sessionがクローズされていない。下記を見る限り、必要そうではある。

http://momijiame.tumblr.com/post/30241416710/python-%E3%81%AE-with-%E6%96%87%E3%81%A7-sqlalchemy-%E3%81%AE%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B

必要なら、sessionのcloseを実装

**Comment by ttskmnj** [comment]
対応しました。
