### ISSUE TITLE
wikiの修正

### ISSUE THREAD

**Issue by Akira-Taniguchi** [Akira-Taniguchi/zaifbot#64]
wikiに下記修正を加えてほしいです

- [ ] 返り値の詳細な説明が欲しいです
- [ ] sma/emaにclosedというキーに1という値が設定されていますが、1が何なのかわかりません。そもそも1ではなくboolea型にしてみてはとおもうのですが、どうでしょうか
- [ ] emaの戻り値のディクショナリの一部がちょっとずれています。正しくフォーマットお願いします

**Comment by ttskmnj** [comment]
修正しました。
